spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-db/table-test    #jdbc:h2:C:/Users/hong/h2-db/table-test
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  #  thymeleaf:
  #    prefix: classpath:/templates/
  #    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create    # ???? table? ????
    properties:
      hibernate:
        #        show_sql: true    # ?????? ???? ???, logger? ?? ?? (system.out?? ???)
        format_sql: true

logging.level:
  org.hibernate.SQL: debug